#include QMK_KEYBOARD_H
#include "version.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


enum custom_keycodes {
#ifdef ORYX_CONFIGURATOR
    VRSN = EZ_SAFE_RANGE,
#else
    VRSN = SAFE_RANGE,
#endif
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox_upsidedown(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_GRV, KC_LALT, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_BSPC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_RALT, KC_CAPS, KC_PGUP, KC_PGDN, MO(2), KC_LGUI, LALT_T(KC_ENT), KC_HOME, KC_UP, LSFT_T(KC_TAB), LT(1,KC_ESC), KC_LEFT, KC_NUBS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, TG(2), KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT, KC_H, KC_J, KC_K, KC_L, KC_MINS, KC_RCTL, TG(1), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, LGUI_T(KC_SCLN), KC_QUOT, KC_LBRC, LSFT(KC_COMM), LSFT(KC_DOT), RALT_T(KC_END), KC_DEL, KC_DOWN, KC_RGHT, KC_BSPC, KC_SPC),
	[1] = LAYOUT_ergodox_upsidedown(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_TRNS, RALT(KC_Q), LSFT(KC_4), RALT(KC_8), RALT(KC_9), KC_GRV, KC_NO, KC_TRNS, KC_NUHS, KC_NUBS, LSFT(KC_8), LSFT(KC_9), LSFT(KC_NUBS), KC_TRNS, KC_NO, KC_EQL, RALT(KC_7), RALT(KC_0), KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_TRNS, LSFT(KC_X), LSFT(KC_C), LSFT(KC_V), KC_PGUP, KC_NO, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_HOME, KC_END, KC_PGDN, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT_ergodox_upsidedown(KC_NO, KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_NO, KC_WH_U, KC_BTN1, KC_MS_U, KC_BTN2, KC_VOLU, KC_BRIU, KC_NO, KC_WH_D, KC_MS_L, KC_MS_D, KC_MS_R, KC_VOLD, KC_BRID, KC_NO, KC_WH_L, KC_BTN3, KC_WH_R, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_P7, KC_P8, KC_P9, KC_PAST, KC_PSLS, KC_TRNS, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_PMNS, KC_TRNS, KC_NLCK, KC_P1, KC_P2, KC_P3, LSFT(KC_0), KC_PDOT, KC_TRNS, KC_P0, KC_PENT, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};




bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            case VRSN:
                SEND_STRING(QMK_KEYBOARD "/" QMK_KEYMAP " @ " QMK_VERSION);
                return false;
        }
    }
    return true;
}

// Runs just one time when the keyboard initializes.
void keyboard_post_init_user(void) {
#ifdef RGBLIGHT_COLOR_LAYER_0
    rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
#endif
};

// Runs whenever there is a layer state change.
layer_state_t layer_state_set_user(layer_state_t state) {
    ergodox_board_led_off();
    ergodox_right_led_1_off();
    ergodox_right_led_2_off();
    ergodox_right_led_3_off();

    uint8_t layer = get_highest_layer(state);
    switch (layer) {
        case 0:
#ifdef RGBLIGHT_COLOR_LAYER_0
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
#endif
            break;
        case 1:
            ergodox_right_led_1_on();
#ifdef RGBLIGHT_COLOR_LAYER_1
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_1);
#endif
            break;
        case 2:
            ergodox_right_led_2_on();
#ifdef RGBLIGHT_COLOR_LAYER_2
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_2);
#endif
            break;
        case 3:
            ergodox_right_led_3_on();
#ifdef RGBLIGHT_COLOR_LAYER_3
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_3);
#endif
            break;
        case 4:
            ergodox_right_led_1_on();
            ergodox_right_led_2_on();
#ifdef RGBLIGHT_COLOR_LAYER_4
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_4);
#endif
            break;
        case 5:
            ergodox_right_led_1_on();
            ergodox_right_led_3_on();
#ifdef RGBLIGHT_COLOR_LAYER_5
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_5);
#endif
            break;
        case 6:
            ergodox_right_led_2_on();
            ergodox_right_led_3_on();
#ifdef RGBLIGHT_COLOR_LAYER_6
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_6);
#endif
            break;
        case 7:
            ergodox_right_led_1_on();
            ergodox_right_led_2_on();
            ergodox_right_led_3_on();
#ifdef RGBLIGHT_COLOR_LAYER_7
            rgblight_setrgb(RGBLIGHT_COLOR_LAYER_7);
#endif
            break;
        default:
            break;
    }

    return state;
};

